### ISSUE TITLE
Add instructions on Heroku and Lambda deployment

### ISSUE THREAD

**Issue by Glogo** [Accenture/alexia#11]
Add instructions to README documenting deployment to Heroku and Lambda

Notes:

**Heroku**
- add script "npm start" to package.json
- create heroku account, install toolbelt, login
- `heroku create [app-name]`
- copy server url to amazon developer portal
- emphasize that heroku requires `process.env.PORT` env variable to be used as server port (it is used by default)

**AWS Lambda**
- create lambda function with handler f.e. `index.handler` and with Alexa Skills Kit trigger
- copy lamba function arn into amazon developer portal
- zip and upload src with bundled node_modules
- (optional) consider creating "zip script" to automate this (upload needs to be manual though)
- add to index.js:

```javascript
/* Create or require app here ... */

exports.handler = (event, context, callback) => {
    app.handle(event, data => {
        callback(null, data);
    });
};
```

**Comment by chrischang** [comment]
How detailed instructions do you want for Heroku? I have just built an app with Alexia and have deployed it to Heroku successfully, so I am wondering maybe if I could help with this task.

**Comment by Glogo** [comment]
Just some basic steps required for the deployment (mentioned in the lists in issue description). I already started writing something for both Heroku and Lambda.

I will create pull request in a minute so you can take a look at it and update it if necessary
