### ISSUE TITLE
Conflicted Information in the README and handle-request.js on responseObject

### ISSUE THREAD

**Issue by chrischang** [Accenture/alexia#14]
In the readme, under "Session Attributes", it states that "Make sure you set end attribute to false to keep the session open (default: true)"

However, after reading through the code, it appeared that this isn't the case.

handle-request.js under createResponse function
```javascript
let responseObject = {
        version: app.options ? app.options.version : '0.0.1',
        sessionAttributes: options.attrs ? options.attrs : attrs,
        response: {
            outputSpeech: outputSpeech,
            shouldEndSession: options.end || false
        }
    };
```

It appeared that the default is false, and I think it should stay like this because when a user says "stop", Alexa should do one of the following:

- Exits the skill.
- The skill returns a response that is appropriate to the skill’s functionality. The response also makes sense in the context of the request to “stop.” For example, a skill that places orders could send back a reply confirming that the user’s order has been canceled.

[Read More 4.13. Stopping and Canceling](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-voice-interface-and-user-experience-testing)

What do you guys think? If you guys agree with this proposal, I could change the README throughout.

**Comment by Glogo** [comment]
Thanks, I did not notice this
Sessions should be ended by default since it is easy to start app with intent directly (f.e. "Alexa ask myapp to say hello").

If developer wants to create intent with on-going session it can be done by returning `end: false` in responseObject

**Comment by Glogo** [comment]
Changed sessions to end by default 2583f8b30dcd5ab901d5eea9b43532614dbc18b8
To keep sessions open it is now required to put `end: false` into responseObject.

In future we may add some sort of global app configuration to change this behaviour
