### ISSUE TITLE
Generate speech assets via NPM scripts

### ISSUE THREAD

**Issue by gonzochic** [Accenture/alexia#19]
I love the idea of generating speech assets automatically. The only thing I find a bit odd is that I can't create them by executing an provided script: e.g. `npm run build-assets`

What do you think?

**Comment by Glogo** [comment]
Yes creating of such script makes sense. The thing is that you need to include this script in the project using alexia, not in the alexia itself.

We are currently working on complete Starter project for alexia and it includes this simple script:
**bin/generate.js**
```javascript
const app = require('path_to_your_app.js');
app.saveSpeechAssets('speechAssets');
```

and in the **package.json**:
```javascript
"scripts"  {
  ...
  "gen": "node ./bin/generate.js"
}
```

so you can run `npm run gen` in your project to generate speech assets

Another option though would be to add CLI to alexia. So running for exapmle: ``alexia gen` or `alexia build-assets` or whatever in your project root would generate speech assets for you.

You would need to specify path to your `app.js` though as parameter

So yes it makes sence to incorporate it into alexia, but for starter maybe just document it in README and then possibly add the CLI. In few weeks when we release Starter project it would be built in it. Would that help?

**Comment by gonzochic** [comment]
I completly agree with you 👍

**Comment by xtools-at** [comment]
> We are currently working on complete Starter project for alexia
Would you give me a sneak preview? I'm not quite sure about a couple of basic things (whereas I'm well off with the documentation on how to use the intents :) ) and a rough project structure could get me started with alexia!

**Comment by Glogo** [comment]
> Would you give me a sneak preview? I'm not quite sure about a couple of basic things (whereas I'm well off with the documentation on how to use the intents :) ) and a rough project structure could get me started with alexia!

@xtools-at it's your lucky day :)
Alexia Starter Kit has just been open sourced. Check out our GitHub repo: https://github.com/Accenture/alexia-starter-kit

**Comment by kubacka** [comment]
@xtools-at check out alexia starter kit repository https://github.com/Accenture/alexia-starter-kit

**Comment by xtools-at** [comment]
thank you very much :)

**Comment by gonzochic** [comment]
As @kubacka said, the feature is now added to the Alexia Start Kit Repo https://github.com/Accenture/alexia-starter-kit

Thx for that 👍
