### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by Glogo** [Accenture/alexia#25]
- extend utterances and slot samples validation to allow characters from German alphabet
- come up with solution how to store multi language utterances, slot samplets

**Comment by Glogo** [comment]
After some analysis we came up with the first multi-language design. This proposition should not bring any breaking changes.

See the details of our suggestions below and please provide us some feedback before we start the implementation.

## 1st multi-language design

**Project structure update**

```
...
└── src/
    ├── modules/...
    └── i10n/                 # (new) directory with all locales
        ├── en-US.js
        ├── en-GB.js
        └── de-DE.js
```
The new directory `src/i10n/` will contain all files with localization

**Locale file contents**
Below are two examples for the localization file for [alexia-starter-kit](https://github.com/Accenture/alexia-starter-kit).

Accessing of the text responses is manual so the structure of those can be altered to suite the needs for given skill.

Note that some responses are functions, returning template strings.

*Option 1 - "Modular"*
```javascript
const dictionaryItems = {
  'car': 'a road vehicle, typically with four wheels',
  'bike': 'a bicycle or motorcycle',
  'house': 'a building for human habitation',
  'pool': 'a small area of still water, typically one formed naturally'
};

module.exports = {
  start: {
    text: 'Welcome to Alexia Starter Kit'
  },
  end: {
    text: 'Goodbye'
  },
  HelloIntent: {
    utterances: ['hello'],
    responses: {
      hello: 'Hello'
    }
  },
  SearchIntent: {
    utterances: [
      'Search for {item:Item}',
      'What is {item:Item}',
      'Describe me {item:Item}'
    ],
    responses: {
      itemError: 'I did not understand your search item',
      resultError: item => `No match found for ${item}`,
      success: (item, definition) => `${item} is ${definition}`
    }
  },
  customSlots: {
    Item: Object.keys(dictionaryItems)
  },
  dictionaryItems
};
```

*Option 2 - "Flat responses"*
```javascript
const dictionaryItems = {
  'car': 'a road vehicle, typically with four wheels',
  'bike': 'a bicycle or motorcycle',
  'house': 'a building for human habitation',
  'pool': 'a small area of still water, typically one formed naturally'
};

module.exports = {
  utterances: {
    HelloIntent: ['hello'],
    SearchIntent: [
      'Search for {item:Item}',
      'What is {item:Item}',
      'Describe me {item:Item}'
    ]
  },
  responses: {
    start: 'Welcome to Alexia Starter Kit',
    end: 'Goodbye',
    hello: 'Hello',
    searchItemError: 'I did not understand your search item',
    searchResultError: item => `No match found for ${item}`,
    searchSuccess: (item, definition) => `${item} is ${definition}`
  },
  customSlots: {
    Item: Object.keys(dictionaryItems)
  },
  dictionaryItems
};
```

The structure of utterances and customSlots has to be fixed for all skills since we need them for the generation of speech assets. Any suggestions?

**Register locales**
In`app.js` add following line. Change the 1st parameter accordingly to match all of your locales
```javascript
app.registerLocales('src/i10n/*.js');
```

**Use locale**
Every Amazon Echo request consists of the property: `request.locale` with the value of for example: `en-US`. Using this value we can pick the right locale for client.

In order to use the correct response (and not be required to deploy application for every locale separately) we will use dynamic locale loader in every intent handler. Localized `HelloIntent` example from alexia-starter-kit:
 
```javascript
module.exports = app => app.intent('HelloIntent', (slots, attrs, data) => {
  const locale = app.getLocale(data.request.locale);
  const responses = locale.HelloIntent.responses; // This is the example for Option 1 locale

  return {
    text: responses.hello
  };
});
```

The `HelloIntent` is defined without the utterances since they will be loaded automatically from the locale files. We will add new method `app.getLocale` that returns the corresponding locale file. Then the user is responsible for picking the correct property from the locale object and use it in the response text

**Speech assets generation**
Speech assets generation for localized apps will rely on the contents of the locales. As mentioned earlier the schema of locale file has to be fixed for utterances and customSlots to enable the speech assets generation

The new `speechAssets` file structure:

```
...
└── speechAssets/
    └── en-US/
        ├── customSlots/
        ├── intentSchema.json
        └── utterances.txt
    └── de-DE/
        ├── customSlots/
        ├── intentSchema.json
        └── utterances.txt
    └── en-GB/
        ├── customSlots/
        ├── intentSchema.json
        └── utterances.txt
```

After generation, the developer copies the localized file contents to the respective skill language section.
I don't believe there is usable option for "flat" structure

---

Please provide us feedback so we can discuss and fine-tune this feature to make it as easy to use as possible.

**Comment by kubacka** [comment]
+1 for 1st option
